locallibrary/catalog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name= 'index'),
    path('books/', views.BookListView.as_view(), name= 'books'),
    path('book/<int:pk>', views.BookDetailList.as_view(), name= 'book-detail'),
    path('authors/', views.AuthorListView.as_view(), name='authors'),
    path('author/<int:pk>', views.AuthorDetailView.as_view(), name='author-detail'),
    path('mybooks/', views.LoanedBooksByUserListView.as_view(), name='my-borrowed'),
    path('borrowed/', views.BorrowedByUserListView.as_view(), name='all-borrowed'),
    path('books/<uuid:pk>/renew', views.renew_book_librarian, name= 'renew-book-librarian'),
    path('author/create/', views.AuthorCreate.as_view(), name= 'author-create'),
    path('author/<int:pk>/update', views.AuthorUpdate.as_view(), name= 'author-update'),
    path('author/<int:pk>/delete', views.AuthorDelete.as_view(), name= 'author-delete'),
    path('book/create', views.BookCreate.as_view(), name= 'book-create'),
    path('book/<int:pk>/update', views.BookUpdate.as_view(), name= 'book-update'),
    path('book/<int:pk>/delete', views.BookDelete.as_view(), name= 'book-delete'),
]

locallibrary/locallibrary/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls')),
    path('', RedirectView.as_view(url= 'catalog/', permanent= True)),
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.STATIC_URL, document_root= settings.STATIC_ROOT)

locallibrary/catalog/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings
from django.contrib.auth.models import User
from datetime import date
from django.contrib.auth.models import PermissionsMixin
import uuid

# Create your models here.

# class User(AbstractUser):
#     pass 

class Genre(models.Model):
    name = models.CharField(max_length= 200, unique= True, help_text="Enter a Book Genre")

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('genre-detail', args=[str(self.id)])
    
    class Meta:
        constraints = [
            models.UniqueConstraint(models.functions.Lower('name'), name= 'genre_name_case_insensitive_unique', violation_error_message= 'Genre already exists (case insensitive match)'),
        ]

class Language(models.Model):
    name = models.CharField(max_length= 200, unique= True, help_text= 'Enter the book\'s natural language (e.g. English, French, Japanese etc.)')

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('language-detail', args=[str(self.id)])
    
    class Meta:
        constraints = [
            models.UniqueConstraint(models.functions.Lower('name'), name= 'language_name_case_insensitive_unique', violation_error_message= 'Language already exists (case insensitive match)'),
        ]

class Book(models.Model):
    title = models.CharField(max_length= 200)
    author = models.ForeignKey('Author', on_delete= models.RESTRICT, null= True)
    summary = models.TextField(max_length= 1000, help_text= 'Enter a brief description of the book')
    isbn = models.CharField('ISBN', max_length= 13, help_text= '13 Character <a href="https://www.isbn-international.org/content/what-isbn''">ISBN number</a>')
    genre = models.ManyToManyField(Genre, help_text='Select a genre for this book')
    language = models.ForeignKey(Language, on_delete=models.SET_NULL, null= True)

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('book-detail', args=[str(self.id)])
    
    def display_genre(self):
        return ', '.join(genre.name for genre in self.genre.all()[:3])
    
    display_genre.short_description = 'genre'
    
class BookInstace(models.Model):
    id = models.UUIDField(primary_key=True, default= uuid.uuid4, help_text= 'Unique ID for this particular book across whole library')
    book = models.ForeignKey(Book, on_delete= models.RESTRICT, null= True)
    imprint = models.CharField(max_length= 200)
    due_back = models.DateField(null= True, blank= True)
    borrower = models.ForeignKey(User, on_delete= models.SET_NULL, null= True, blank= True)

    @property
    def is_overdue(self):
        return bool(self.due_back and date.today() > self.due_back)

    LOAN_STATUS = (
        ('m', 'Maintenance'),
        ('o', 'On loan'),
        ('a', 'Available'),
        ('r', 'Reserved'),
    )

    status = models.CharField(max_length= 1, choices= LOAN_STATUS, blank= True, default= 'm', help_text= 'Book availability')

    def __str__(self):
        return '{} ({})'.format(self.id, self.book.title)

    class Meta:
        ordering = ['due_back']
        permissions = (('can_mark_returned', 'Set book as returned'),)

class Author(models.Model):
    first_name = models.CharField(max_length= 100)
    last_name = models.CharField(max_length= 100)
    date_of_birth = models.DateField(null= True, blank= True)
    date_of_death = models.DateField('Died', null= True, blank= True)

    def __str__(self):
        return '{}, {}'.format(self.first_name, self.last_name)
    
    def get_absolute_url(self):
        return reverse('author-detail', args=[str(self.id)])
    
    class Meta:
        ordering = ['last_name', 'first_name']

locallibrary/catalog/forms.py
import datetime
from django import forms
from django.forms import ModelForm
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
from catalog.models import BookInstace


class RenewBookModelForm(ModelForm):
    def clean_renewal_date(self):
        data = self.cleaned_data['due_back']

        if data < datetime.date.today():
            raise ValidationError(_('Invalid date - renewal in past'))
        
        if data > datetime.date.today() + datetime.timedelta(weeks= 4):
            raise ValidationError(_('Invalid date - renewal more than 4 weeks'))
        
        return data
    
    class Meta:
        model = BookInstace
        fields = ['due_back']
        label = {'due_back': _('renewal_date')}
        help_texts = {'due_back': _('Enter a date between now and 4 weeks (default 3).')}

class RenewBookForm(forms.Form):
    renewal_date = forms.DateField(help_text= 'Enter a date between now and 4 weeks (default 3).')

    def clean_renewal_date(self):
        data = self.cleaned_data['renewal_date']
    
        if data < datetime.date.today():
            raise ValidationError(_('Invalid date - renewal in past'))
        
        if data > datetime.date.today() + datetime.timedelta(weeks= 4):
            raise ValidationError(_('Invalid date - renewal more than 4 weeks'))
            
        
        return data

locallibrary/catalog/views.py
import datetime
from typing import Any
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.db.models.query import QuerySet
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponseRedirect
from django.views import generic
from django.urls import reverse, reverse_lazy
from django.contrib.auth.mixins import PermissionRequiredMixin,LoginRequiredMixin
from django.contrib.auth.decorators import login_required, permission_required
from .models import Book, BookInstace, Author, Genre
from catalog.forms import RenewBookForm



@login_required
@permission_required('catalog.can_mark_renewal', raise_exception= True)
def renew_book_librarian(request, pk):
    book_instance = get_object_or_404(BookInstace, pk=pk)

    if request.method == 'POST':
        form = RenewBookForm(request.POST)

        if form.is_valid():
            book_instance.due_back = form.cleaned_data['renewal_date']
            book_instance.save()

            return HttpResponseRedirect(reverse('all-borrowed'))
    else:
        proposed_renewal_date = datetime.date.today() + datetime.timedelta(weeks= 3)
        form = RenewBookForm(initial={'renewal_date': proposed_renewal_date})

    context = {
        'form': form,
        'book_instance': book_instance,
    }

    return render(request, 'catalog/book_renew_librarian.html', context)

def index(request):

    num_books = Book.objects.all().count()
    num_instance = BookInstace.objects.all().count()

    num_status = BookInstace.objects.filter(status__exact= 'a').count()

    num_author = Author.objects.all().count()
    num_genre = Genre.objects.all().count()

    filtered_book = Book.objects.filter(title__contains= 'teke').count()
    
    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits + 1

    context = {
        'num_books': num_books,
        'num_instance': num_instance,
        'num_status': num_status,
        'num_authors': num_author,
        'num_genres': num_genre,
        'num_filtered_books': filtered_book,
        'num_visits': num_visits,
    }

    return render(request, 'catalog/index.html', context)


class BookListView(generic.ListView):
    model = Book
    paginate_by = 2
    # context_object_name = 'book_list'
    # template_name = 'books/my_arbitrary_template_list_name.html'

    # def get_queryset(self):
    #     return Book.objects.filter(title__icontains= 'teke')[:5]
class BookDetailList(generic.DetailView):
    model = Book

class AuthorListView(generic.ListView):
    model = Author

class AuthorDetailView(generic.DetailView):
    model = Author

class LoanedBooksByUserListView(LoginRequiredMixin, generic.ListView):
    model = BookInstace
    template_name = 'catalog/bookinstance_list_borrowed_user.html'
    paginate_by = 10

    def get_queryset(self):
        return (
            BookInstace.objects.filter(borrower = self.request.user)
            .filter(status__exact = 'o')
            .order_by('due_back')
        )

class BorrowedByUserListView(PermissionRequiredMixin, generic.ListView):
    model = BookInstace
    template_name = 'catalog/all_borrowed_books.html'
    paginate_by = 3
    permission_required = ('catalog/can_mark_returned')

    def get_queryset(self):
        return BookInstace.objects.filter(status__exact = 'o').order_by('due_back')
    
class AuthorCreate(PermissionRequiredMixin, CreateView):
    model = Author
    fields = ['first_name', 'last_name', 'date_of_birth', 'date_of_death']
    initial = {'date_of_death': '11/11/2023'}
    permission_required = 'catalog.add_auther'

class AuthorUpdate(PermissionRequiredMixin, UpdateView):
    model = Author
    fields = ['first_name', 'last_name', 'date_of_birth', 'date_of_death']
    permission_required = 'catalog.change_author'

class AuthorDelete(PermissionRequiredMixin, DeleteView):
    model = Author
    success_url = reverse_lazy('authors')
    permission_required = 'catalog.delete_author'

    def form_valid(self, form):
        try:
            self.object.delete()
            return HttpResponseRedirect(self.success_url)
        except Exception as e: 
            return HttpResponseRedirect(reverse('author-delete', kwargs={'pk': self.object.pk}))
        
class BookCreate(PermissionRequiredMixin, CreateView):
    model = Book
    fields = ['title', 'author', 'summary', 'isbn', 'genre', 'language']
    permission_required = 'catalog.add_book'

class BookUpdate(PermissionRequiredMixin, UpdateView):
    model = Book 
    fields = ['title', 'author', 'summary', 'isbn', 'genre', 'language']
    permission_required = 'catalog.change_book'

class BookDelete(PermissionRequiredMixin, DeleteView):
    model = Book
    success_url = reverse_lazy('books')
    permission_required = 'catalog.delete_book'

    def form_valid(self, form):
        try:
            self.object.delete()
            return HttpResponseRedirect(self.success_url)
        except:
            return HttpResponseRedirect(reverse('book-delete', kwargs= {'pk': self.object.pk}))

locallibrary/catalog/templates/catalog/all_borrowed_books.html
{% extends "./base_generic.html" %}

{% block content %}
   <h1 style="margin-bottom: 25px;">All Borrowed Books</h1>
    {% if perms.catalog.can_mark_returned %}
        <ul>
            {% for book in bookinstace_list %}
                <li class="{% if book.is_overdue %}text-danger{% endif %}"><a href="{% url 'book-detail' book.book.pk %}">{{ book.book }}</a> ({{ book.due_back }}) - {{ book.borrower }}- <a href="{% url 'renew-book-librarian' book.id%}">Renew</a>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>You don't have permission to see this section</p>
    {% endif %}
{% endblock %}

locallibrary/catalog/templates/catalog/author_confirm_delete.html
{% extends "./base_generic.html" %}

{% block content %}
    <h1>Delete Author: {{ author }}</h1>
    {% if author.book_set.all %}
        <p>You can't delete this author until all their books have been deleted:</p>
        <ul>
            {% for book in author.book_set.all %}
                <li><a href="{% url 'book-detail' book.pk %}">{{ book }}</a> ({{ book.bookinstace_set.all.count }})</li>
            {% endfor %}
        </ul>
    {% else %}
        <p>Are you sure you want to delete this author ?</p>
        <form action="" method="post">
            {% csrf_token %}
            <input type="submit" value="Yes, delete.">
        </form>
    {% endif %}
{% endblock %}

locallibrary/catalog/templates/catalog/author_detail.html
{% extends "./base_generic.html" %}

{% block content %}
    <h1 style="margin-top: 20px;">Author: {{ author.last_name }}, {{ author.first_name }}</h1>
    <p>{{ author.date_of_birth }} - {{ author.date_of_death }}</p>
    <div style="margin-top: 20px; margin-left: 20px;">
        <h4>Books</h4>
        {% for auth in author.book_set.all %}
        <a href="{% url 'book-detail' auth.pk %}">{{ auth }}</a> <strong>({{ auth.bookinstace_set.count }}) </strong>
        <p>{{ auth.summary }}</p>
        {% empty %}
        <p>This author has no any books</p>
        {% endfor %}
    </div>
{% endblock %}

{% block sidebar %}
    {{ block.super }}
    {% if perms.catalog.change_author or perms.catalog.delete_author %}
        <hr>
        <ul class="sidebar-nav">
            {% if perms.catalog.chhange_author %}
                <li><a href="{% url 'author-update' author.id %}">Update author</a></li>
            {% endif %}
            {% if not author.book_set.all and perms.catalog.delete_author %}
                <li><a href="{% url 'author-delete' author.id %}">Delete author</a></li>
            {% endif %}
        </ul>
    {% endif %}
{% endblock %}

locallibrary/catalog/templates/catalog/author_form.html
{% extends "./base_generic.html" %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        <table>
        {{ form.as_table }}
        </table>        
        <input type="submit" value="Submit">
    </form>
{% endblock %}

locallibrary/catalog/templates/catalog/author_list.html
{% extends "./base_generic.html" %}

{% block content %}
    <h1>Author List</h1>
    {% if author_list%}
        <ul>
            {% for author in author_list %}
            <a href="{% url 'author-detail' author.pk%}"><li>{{ author.last_name }}, {{ author.first_name }} ({{ author.date_of_birth }} - {{ author.date_of_death }})</li></a>
            {% endfor %}
        </ul>
    {% else %}
        <p>There are no any Authors!</p>
    {% endif %}
{% endblock %}

locallibrary/catalog/templates/catalog/base_generic.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% block title %}
      <title>Local Library</title>
    {% endblock %}
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
      crossorigin="anonymous">
    <!-- Add additional CSS in static file -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
  </head>
  <body>
    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-2">
          {% block sidebar %}
            <ul class="sidebar-nav">
              <li><a href="{% url 'index' %}">Home</a></li>
              <li><a href="{% url 'books' %}">All books</a></li>
              <li><a href="{% url 'authors' %}">All authors</a></li>
              {% if user.is_authenticated %}
                <li style="margin-top: 30px;">User: {{ user.get_username }}</li>
                <li><a href="{% url 'my-borrowed' %}">My borrowed</a></li>
                <li>
                  <form id="logout-form" method="post" action="{% url 'logout' %}">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-link">Logout</button>
                  </form>
                </li>
                <hr style="margin-top: 50px; margin-bottom: 50px;">
                {% if perms.catalog.can_mark_returned %}
                  <li>Staff</li>
                  <li><a href="{% url 'all-borrowed' %}">All borrowed</a></li>
                  {% if perms.catalog.add_author %}
                    <li><a href="{% url 'author-create' %}">Create author</a></li>
                  {% endif %}
                  {% if perms.catalog.add_book %}
                    <li><a href="{% url 'book-create' %}">Create book</a></li>
                  {% endif %}
                {% endif %}
              {% else %}
                <li><a href="{% url 'login' %}?next={{ request.path }}">Login</a></li>
              {% endif %}
            </ul>
          {% endblock %}
        </div>
        <div class="col-sm-10 ">{% block content %}{% endblock %}
          {% block pagination %}
            {% if is_paginated %}
              <div class="pagination">
                <span class="page-links">
                  {% if page_obj.has_previous %}
                    <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
                  {% endif %}
                  <span class="page-current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                  </span>
                  {% if page_obj.has_next %}
                    <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
                  {% endif %}
                </span>
              </div>
            {% endif %}
          {% endblock %}
        </div>
      </div>
    </div>
  </body>
</html>

locallibrary/catalog/templates/catalog/book_confirm_delete.html
{% extends "./base_generic.html" %}

{% block content %}
    <h1>Delete Book: {{ book }}</h1>
    {% if book.bookinstace_set.all %}
        <p>You can't delete this book until all their book instances have been deleted:</p>
        <ul>
            {% for bookinst in book.booinstace_set.all %}
                <li><a href="{% url 'book-detail' book.pk %}">{{ book }}</a>({{ bookinst.object.all.count }})</li>
            {% endfor %}
        </ul>
    {% else %}
        <p>Are you sure you want to delte this book?</p>
        <form action="" method="post">
            {% csrf_token %}
            <input type="submit" value="Submit">
        </form>
    {% endif %}
{% endblock %}

locallibrary/catalog/templates/catalog/book_detail.html
{% extends "./base_generic.html" %}

{% block content %}
    <h1>Title: {{ book.title }}</h1>
    <p><strong>Author: <a href="{{ book.atuhor.get_absolute_url }}">{{ book.author }}</a></strong></p>
    <p><strong>Summary:</strong> {{ book.summary }}</p>
    <p><strong>ISBN: </strong> {{ book.isbn }}</p>
    <p><strong>Genre: </strong> {{ book.genre.all|join:", " }}</p>
    <p><strong>Language: </strong> {{ book.language }}</p>

    <div style="margin-left: 20px; margin-top: 20px;">
        <h4>Copies</h4>
        {% for copy in book.bookinstace_set.all %}
            <p>salam</p>
            <hr/>
            <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'm' %}text-danger{% else %}text-warning{% endif %}">
                {{ copy.get_status_display }}
            </p>
            {% if copy.status != 'a' %}
            <p><strong>Due to be back:</strong> {{ copy.due_back }}</p>
            {% endif %}
            <p><strong>Imprint:</strong> {{ copy.imprint }}</p>
            <p class="text-muted"><strong>ID:</strong> {{ copy.id }}</p>
        {% endfor %}
    </div>
{% endblock %}

{% block sidebar %}
    {{ block.super }}
    {% if perms.catalog.change_book or perms.catalog.delete_book %}
    <hr>
    <ul class="sidebar-nav">
        {% if perms.catalog.change_book %}
            <li><a href="{% url 'book-update' book.pk %}">Update book</a></li>
        {% endif %}
        {% if not book.bookinstace_set.all.count and perms.catalog.delete_book %}
            <li><a href="{%url 'book-delete' book.pk %}">Delete book</a></li>
        {% endif %}
    </ul>
    {% endif %}
{% endblock %}

locallibrary/catalog/templates/catalog/book_form.html
{% extends "./base_generic.html" %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="Submit">
    </form>
{% endblock %}

locallibrary/catalog/templates/catalog/book_list.html
{% extends "./base_generic.html" %}

{% block content %}
    <h1>Book List</h1>
    {% if book_list %}
    <ul>
        {% for book in book_list %}
            <li>
                <a href="{{ book.get_absolute_url }}">{{ book.title }}</a>
                ({{ book.author }})
            </li>
        {% endfor %}
    </ul>
    {% else %}
        <p>There are no any books in library!</p>
    {% endif %}
{% endblock %}

locallibrary/catalog/templates/catalog/book_renew_librarian.html
{% extends "./base_generic.html" %}

{% block content %}
    <h1>Book: {{ book_instance.book.title }}</h1>
    <h1>Borrower: {{ book_instance.borrower }}</h1>
    <p {% if book_instance.is_overdue %} class="text-danger" {% endif %}>Due date: {{ book_instance.due_back }}</p>

    <form action="" method="post">
        {% csrf_token %}
        <table>
            {{ form.as_table}}
        </table>
        <input type="submit" value="Submit">
    </form>
{% endblock %}

locallibrary/catalog/templates/catalog/bookinstance_list_borrowed_user.html
{% extends "./base_generic.html" %}

{% block content %}
    <title>Borrowed Books</title>
    {% if bookinstace_list %}
        <ul>
            {% for bookinst in bookinstace_list %}
                <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
                    <a href="{% url 'book-detail' bookinst.book.pk %}">{{ bookinst.book }}</a>
                    {{ bookinst.due_back }}
                </li>
            {% endfor%}
        </ul>
        
    {% else %}
        <p>There is no borrowed book</p>
    {% endif %}


{% endblock %}

locallibrary/catalog/templates/catalog/index.html
{% extends "./base_generic.html" %}

{% block content %}
  <h1>Local Library Home</h1>
  <p>
    Welcome to LocalLibrary, a website developed by
    <em>Ronago</em>!
  </p>
  <h2>Dynamic content</h2>
  <p>The library has the following record counts:</p>
  <ul>
    <li><strong>Books:</strong> {{ num_books }}</li>
    <li><strong>Copies:</strong> {{ num_instance }}</li>
    <li><strong>Copies available:</strong> {{ num_status }}</li>
    <li><strong>Authors:</strong> {{ num_authors }}</li>
    <li><strong>Genres:</strong> {{ num_genres }}</li>
    <li><strong>Filtered by "teke":</strong> {{ num_filtered_books }}</li>
  </ul>

  <p>
    You have visited this page {{ num_visits }} time{{ num_visits|pluralize }}.
  </p>
{% endblock %}